package com.stpl.trainee.assignment9.bean;


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * StudentRegister generated by hbm2java
 */
@Entity
@Table(name = "Student_Register", schema = "dbo", catalog = "BPIGTN_TRAINEE")
public class StudentRegister implements java.io.Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = 1L;
    private String username;
    private String fullname;
    private String pasword;
    private String address;
    private String dob;
    private String gender;
    private String email;
    private String contact;
    private String city;
    private String state;
    private String country;
    private String coursename;
    private String courseid;
    private String fees;
    private String duration;

    public StudentRegister() {
        //Do nothing, only to create object
    }

    public StudentRegister(String username) {
        this.username = username;
    }

    public StudentRegister(String username, String fullname, String pasword, String address, String dob, String gender,
            String email, String contact, String city, String state, String country, String coursename, String courseid,
            String fees, String duration) {
        this.username = username;
        this.fullname = fullname;
        this.pasword = pasword;
        this.address = address;
        this.dob = dob;
        this.gender = gender;
        this.email = email;
        this.contact = contact;
        this.city = city;
        this.state = state;
        this.country = country;
        this.coursename = coursename;
        this.courseid = courseid;
        this.fees = fees;
        this.duration = duration;
    }

    @Id

    @Column(name = "username", unique = true, nullable = false, length = 50)
    public String getUsername() {
        return this.username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    @Column(name = "fullname", length = 50)
    public String getFullname() {
        return this.fullname;
    }

    public void setFullname(String fullname) {
        this.fullname = fullname;
    }

    @Column(name = "pasword", length = 30)
    public String getPasword() {
        return this.pasword;
    }

    public void setPasword(String pasword) {
        this.pasword = pasword;
    }

    @Column(name = "address", length = 100)
    public String getAddress() {
        return this.address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    @Column(name = "dob", length = 10)
    public String getDob() {
        return this.dob;
    }

    public void setDob(String dob) {
        this.dob = dob;
    }

    @Column(name = "gender", length = 10)
    public String getGender() {
        return this.gender;
    }

    public void setGender(String gender) {
        this.gender = gender;
    }

    @Column(name = "email", length = 30)
    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    @Column(name = "contact", length = 10)
    public String getContact() {
        return this.contact;
    }

    public void setContact(String contact) {
        this.contact = contact;
    }

    @Column(name = "city", length = 50)
    public String getCity() {
        return this.city;
    }

    public void setCity(String city) {
        this.city = city;
    }

    @Column(name = "state", length = 50)
    public String getState() {
        return this.state;
    }

    public void setState(String state) {
        this.state = state;
    }

    @Column(name = "country", length = 50)
    public String getCountry() {
        return this.country;
    }

    public void setCountry(String country) {
        this.country = country;
    }

    @Column(name = "coursename", length = 50)
    public String getCoursename() {
        return this.coursename;
    }

    public void setCoursename(String coursename) {
        this.coursename = coursename;
    }

    @Column(name = "courseid", length = 50)
    public String getCourseid() {
        return this.courseid;
    }

    public void setCourseid(String courseid) {
        this.courseid = courseid;
    }

    @Column(name = "fees", length = 20)
    public String getFees() {
        return this.fees;
    }

    public void setFees(String fees) {
        this.fees = fees;
    }

    @Column(name = "duration", length = 20)
    public String getDuration() {
        return this.duration;
    }

    public void setDuration(String duration) {
        this.duration = duration;
    }

}
